services:
  backend:
    image: gurmeetpunia/ai-sql-backend:latest

    container_name: ai-sql-backend

    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      - ai-network


  frontend:
    image: gurmeetpunia/ai-sql-frontend:latest

    container_name: ai-sql-frontend

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot

    depends_on:
      backend:
        condition: service_healthy

    networks:
      - ai-network
networks:
  ai-network:
    driver: bridge